services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "8087:80"
    networks:
      - dweb-network
networks:
  dweb-network:
    driver: bridge
